 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/checkouts", type: :request do
  
  # Checkout. As you add validations to Checkout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Checkout.create! valid_attributes
      get checkouts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      checkout = Checkout.create! valid_attributes
      get checkout_url(checkout)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_checkout_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      checkout = Checkout.create! valid_attributes
      get edit_checkout_url(checkout)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Checkout" do
        expect {
          post checkouts_url, params: { checkout: valid_attributes }
        }.to change(Checkout, :count).by(1)
      end

      it "redirects to the created checkout" do
        post checkouts_url, params: { checkout: valid_attributes }
        expect(response).to redirect_to(checkout_url(Checkout.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Checkout" do
        expect {
          post checkouts_url, params: { checkout: invalid_attributes }
        }.to change(Checkout, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post checkouts_url, params: { checkout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested checkout" do
        checkout = Checkout.create! valid_attributes
        patch checkout_url(checkout), params: { checkout: new_attributes }
        checkout.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the checkout" do
        checkout = Checkout.create! valid_attributes
        patch checkout_url(checkout), params: { checkout: new_attributes }
        checkout.reload
        expect(response).to redirect_to(checkout_url(checkout))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        checkout = Checkout.create! valid_attributes
        patch checkout_url(checkout), params: { checkout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested checkout" do
      checkout = Checkout.create! valid_attributes
      expect {
        delete checkout_url(checkout)
      }.to change(Checkout, :count).by(-1)
    end

    it "redirects to the checkouts list" do
      checkout = Checkout.create! valid_attributes
      delete checkout_url(checkout)
      expect(response).to redirect_to(checkouts_url)
    end
  end
end
